# Generated by Django 5.0.7 on 2024-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='live_stream_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
