# Generated by Django 5.1 on 2024-09-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_type',
            field=models.CharField(choices=[('nba', 'NBA Streams'), ('nhl', 'NHL Streams'), ('mlb', 'MLB Streams'), ('mma', 'MMA Streams'), ('boxing', 'Boxing Streams'), ('nfl', 'NFL Streams'), ('cfb', 'CFB Streams'), ('motor_sports', 'Motor Sports Streams'), ('soccer', 'Soccer Streams')], default='soccer', max_length=50),
        ),
    ]
