# Generated by Django 5.0.7 on 2024-08-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_description_alter_match_live_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
