# Generated by Django 5.1 on 2024-09-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
    ]
