# Generated by Django 5.0.7 on 2024-08-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
