# Generated by Django 5.0.7 on 2024-08-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team2_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_name',
            field=models.CharField(default='Team A', max_length=100),
            preserve_default=False,
        ),
    ]
